"""Shared speaker-verification contracts and DTOs."""

from __future__ import annotations

import os
import re
from collections.abc import Sequence
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol

_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def validate_voiceprint_id(value: str, *, label: str, max_len: int = 64) -> str:
    if not (1 <= len(value) <= max_len) or not _ID_RE.match(value):
        raise ValueError(f"{label} must be 1-{max_len} chars of [A-Za-z0-9_-]")
    return value


def default_profile_id(user_id: str) -> str:
    return f"vp_{validate_voiceprint_id(user_id, label='user_id')}_default"


def default_voiceprint_root() -> Path:
    """Default shared location for local voiceprint metadata and profiles."""
    env = os.environ.get("EIDOLON_VOICEPRINT_ROOT", "").strip()
    if env:
        return Path(env).expanduser()
    state_root = Path(os.environ.get("EIDOLON_STATE_ROOT", "~/eidolon/data")).expanduser()
    return state_root / "voiceprints"


@dataclass(frozen=True)
class SpeakerSignal:
    """Observe-only speaker identity result for one user turn."""

    provider: str
    model: str
    speaker_user_id: str | None = None
    known: bool = False
    owner_confidence: float | None = None
    score: float | None = None
    latency_ms: float | None = None
    audio_ms: int | None = None
    profile_id: str | None = None
    error: str | None = None

    @classmethod
    def error_signal(
        cls,
        *,
        provider: str,
        model: str,
        error: str,
        latency_ms: float | None = None,
        audio_ms: int | None = None,
        profile_id: str | None = None,
    ) -> "SpeakerSignal":
        return cls(
            provider=provider,
            model=model,
            known=False,
            latency_ms=latency_ms,
            audio_ms=audio_ms,
            profile_id=profile_id,
            error=error,
        )

    def as_timeline_attrs(self) -> dict[str, Any]:
        """Return a compact JSON-serializable payload for timeline attrs."""
        return {k: v for k, v in asdict(self).items() if v is not None}


@dataclass(frozen=True)
class VoiceprintEmbedding:
    """Persisted profile embedding generated by admin enrollment."""

    profile_id: str
    tenant_id: str
    user_id: str
    provider: str
    model: str
    vector: tuple[float, ...]
    dim: int
    dtype: str = "float32"
    pooling: str = "mean_l2_normalized"
    sample_refs: tuple[str, ...] = ()
    sample_rate: int = 16000
    created_at: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "VoiceprintEmbedding":
        payload = dict(data)
        payload["vector"] = tuple(float(value) for value in payload.get("vector") or ())
        payload["sample_refs"] = tuple(payload.get("sample_refs") or ())
        return cls(**payload)


@dataclass(frozen=True)
class VoiceprintProfile:
    """Metadata for a locally stored user voiceprint profile."""

    profile_id: str
    tenant_id: str
    user_id: str
    provider: str
    model: str
    embedding_ref: str = ""
    sample_refs: tuple[str, ...] = ()
    sample_rate: int = 16000
    duration_ms: int = 0
    threshold: float | None = None
    quality: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=utc_now)
    updated_at: str = field(default_factory=utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        validate_voiceprint_id(self.profile_id, label="profile_id", max_len=128)
        validate_voiceprint_id(self.tenant_id, label="tenant_id")
        validate_voiceprint_id(self.user_id, label="user_id")

    def to_json(self) -> dict[str, Any]:
        data = asdict(self)
        data["sample_refs"] = list(self.sample_refs)
        return data

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "VoiceprintProfile":
        payload = dict(data)
        payload["sample_refs"] = tuple(payload.get("sample_refs") or ())
        return cls(**payload)


class SpeakerVerificationProvider(Protocol):
    """Minimal async contract shared by noop and real voiceprint providers."""

    @property
    def provider(self) -> str: ...

    @property
    def model(self) -> str: ...

    async def enroll(
        self,
        *,
        tenant_id: str,
        user_id: str,
        audio_segments: Sequence[bytes],
        sample_rate: int,
    ) -> VoiceprintProfile:
        """Create a profile from enrollment PCM/WAV bytes."""

    async def verify(
        self,
        *,
        audio: bytes,
        sample_rate: int,
        profiles: Sequence[VoiceprintProfile],
        audio_ms: int | None = None,
    ) -> SpeakerSignal:
        """Return the best speaker match for one voiced turn."""
