# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eidolon.channel.livekit.agent.remote_agent_rpc.v1.grpc_gen import remote_agent_rpc_pb2 as eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in eidolon/channel/livekit/agent/remote_agent_rpc/v1/grpc_gen/remote_agent_rpc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RemoteAgentStub(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/eidolon.channel.livekit.agent.remote_agent_rpc.v1.grpc_gen.RemoteAgent/Session',
                request_serializer=eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ClientMessage.SerializeToString,
                response_deserializer=eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ServerMessage.FromString,
                _registered_method=True)


class RemoteAgentServicer(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    def Session(self, request_iterator, context):
        """One long-lived logical session per voice room / job. Client may open a
        new RPC per utterance (simple) or reuse one stream (advanced); v1 keeps
        semantics minimal: server MUST handle Config + UserTurn per RPC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ClientMessage.FromString,
                    response_serializer=eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'eidolon.channel.livekit.agent.remote_agent_rpc.v1.grpc_gen.RemoteAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('eidolon.channel.livekit.agent.remote_agent_rpc.v1.grpc_gen.RemoteAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RemoteAgent(object):
    """---------------------------------------------------------------------------
    Service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/eidolon.channel.livekit.agent.remote_agent_rpc.v1.grpc_gen.RemoteAgent/Session',
            eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ClientMessage.SerializeToString,
            eidolon_dot_channel_dot_livekit_dot_agent_dot_remote__agent__rpc_dot_v1_dot_grpc__gen_dot_remote__agent__rpc__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
