"""Filesystem-backed voiceprint profile metadata store."""

from __future__ import annotations

import json
import os
import re
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

_ID_RE = re.compile(r"^[A-Za-z0-9_-]+$")


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _validate_id(value: str, *, label: str, max_len: int = 64) -> str:
    if not (1 <= len(value) <= max_len) or not _ID_RE.match(value):
        raise ValueError(f"{label} must be 1-{max_len} chars of [A-Za-z0-9_-]")
    return value


def default_profile_id(user_id: str) -> str:
    return f"vp_{_validate_id(user_id, label='user_id')}_default"


def default_voiceprint_root() -> Path:
    """Default shared location for local voiceprint metadata and profiles."""
    env = os.environ.get("EIDOLON_VOICEPRINT_ROOT", "").strip()
    if env:
        return Path(env).expanduser()
    return Path.home() / "eidolon" / "voiceprints"


@dataclass(frozen=True)
class VoiceprintEmbedding:
    """Persisted profile embedding generated by admin enrollment."""

    profile_id: str
    tenant_id: str
    user_id: str
    provider: str
    model: str
    vector: tuple[float, ...]
    dim: int
    dtype: str = "float32"
    pooling: str = "mean_l2_normalized"
    sample_refs: tuple[str, ...] = ()
    sample_rate: int = 16000
    created_at: str = field(default_factory=_utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "VoiceprintEmbedding":
        payload = dict(data)
        payload["vector"] = tuple(float(value) for value in payload.get("vector") or ())
        payload["sample_refs"] = tuple(payload.get("sample_refs") or ())
        return cls(**payload)


@dataclass(frozen=True)
class VoiceprintProfile:
    """Metadata for a locally stored user voiceprint profile."""

    profile_id: str
    tenant_id: str
    user_id: str
    provider: str
    model: str
    embedding_ref: str = ""
    sample_refs: tuple[str, ...] = ()
    sample_rate: int = 16000
    duration_ms: int = 0
    threshold: float | None = None
    quality: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=_utc_now)
    updated_at: str = field(default_factory=_utc_now)
    metadata: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        _validate_id(self.profile_id, label="profile_id", max_len=128)
        _validate_id(self.tenant_id, label="tenant_id")
        _validate_id(self.user_id, label="user_id")

    def to_json(self) -> dict[str, Any]:
        data = asdict(self)
        data["sample_refs"] = list(self.sample_refs)
        return data

    @classmethod
    def from_json(cls, data: dict[str, Any]) -> "VoiceprintProfile":
        payload = dict(data)
        payload["sample_refs"] = tuple(payload.get("sample_refs") or ())
        return cls(**payload)


class VoiceprintStore:
    """Small JSON metadata store under ``root/tenant_id/user_id``."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).expanduser()

    def profile_path(
        self,
        *,
        tenant_id: str,
        user_id: str,
        profile_id: str | None = None,
    ) -> Path:
        tenant_id = _validate_id(tenant_id, label="tenant_id")
        user_id = _validate_id(user_id, label="user_id")
        if profile_id is None or profile_id == default_profile_id(user_id):
            return self.root / tenant_id / user_id / "profile.json"
        profile_id = _validate_id(profile_id, label="profile_id", max_len=128)
        return self.root / tenant_id / user_id / f"{profile_id}.json"

    def save_profile(self, profile: VoiceprintProfile) -> Path:
        path = self.profile_path(
            tenant_id=profile.tenant_id,
            user_id=profile.user_id,
            profile_id=profile.profile_id,
        )
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(profile.to_json(), ensure_ascii=False, indent=2)
            + "\n",
            encoding="utf-8",
        )
        return path

    def load_profile(
        self,
        *,
        tenant_id: str,
        user_id: str,
        profile_id: str | None = None,
    ) -> VoiceprintProfile | None:
        path = self.profile_path(
            tenant_id=tenant_id,
            user_id=user_id,
            profile_id=profile_id,
        )
        if not path.exists() and profile_id is None:
            legacy = (
                self.root
                / _validate_id(tenant_id, label="tenant_id")
                / _validate_id(user_id, label="user_id")
                / f"{default_profile_id(user_id)}.json"
            )
            path = legacy
        if not path.exists():
            return None
        return VoiceprintProfile.from_json(json.loads(path.read_text(encoding="utf-8")))

    def list_user_profiles(
        self,
        *,
        tenant_id: str,
        user_id: str,
    ) -> list[VoiceprintProfile]:
        base = self.profile_path(tenant_id=tenant_id, user_id=user_id).parent
        if not base.exists():
            return []
        profiles: list[VoiceprintProfile] = []
        for path in sorted(base.glob("*.json")):
            profiles.append(
                VoiceprintProfile.from_json(
                    json.loads(path.read_text(encoding="utf-8"))
                )
            )
        return profiles

    def embedding_path(self, profile: VoiceprintProfile) -> Path | None:
        if not profile.embedding_ref:
            return None
        path = (self.root / profile.embedding_ref).expanduser().resolve()
        root = self.root.expanduser().resolve()
        try:
            path.relative_to(root)
        except ValueError as exc:
            raise ValueError(f"embedding_ref escapes voiceprint root: {profile.embedding_ref}") from exc
        return path

    def load_embedding(self, profile: VoiceprintProfile) -> VoiceprintEmbedding | None:
        path = self.embedding_path(profile)
        if path is None or not path.exists():
            return None
        return VoiceprintEmbedding.from_json(json.loads(path.read_text(encoding="utf-8")))

    def delete_profile(
        self,
        *,
        tenant_id: str,
        user_id: str,
        profile_id: str | None = None,
    ) -> bool:
        path = self.profile_path(
            tenant_id=tenant_id,
            user_id=user_id,
            profile_id=profile_id,
        )
        if not path.exists():
            return False
        path.unlink()
        return True
